---
name: install utilites 
hosts: yes
tasks: 
  - name: install utilites 
    ansible.builtin.packages:
      name: "{{ item }}"
      state: yes
      loop: "{{ packages }}"
  - name: debug variables
    ansible.builtin.debug:
      var: purpose
  - name: the configuration file of ansible
    ansible.builtin.debug:
      var: ansible_config_file
  - name: inventory file name 
    ansible.builtin.debug:
      var: inventory_file